//
//  ColorScheme+Extensions.swift
//  FitnessApp
//
//  Created on 12/21/25.
//

import SwiftUI

extension Color {
    
    // MARK: - App Colors
    // Note: primaryBackground, secondaryBackground, cardBackground, and accentColor
    // are auto-generated by Xcode from Assets.xcassets
    
    // MARK: - Insight Colors
    
    static let insightOrange = Color.orange
    static let insightGold = Color.yellow
    static let insightBlue = Color.blue
    static let insightPurple = Color.purple
    
    // MARK: - Status Colors
    
    static let successGreen = Color.green
    static let errorRed = Color.red
    static let warningYellow = Color.yellow
    
    // MARK: - Helper Methods
    
    /// Returns true if the current color scheme is dark mode
    static func isDarkMode(_ colorScheme: ColorScheme) -> Bool {
        return colorScheme == .dark
    }
}

extension View {
    
    /// Apply adaptive foreground color based on color scheme
    func adaptiveForeground(_ colorScheme: ColorScheme) -> some View {
        self.foregroundColor(colorScheme == .dark ? .white : .black)
    }
    
    /// Apply card style with adaptive background
    func cardStyle() -> some View {
        self
            .background(Color.cardBackground)
            .cornerRadius(12)
            .shadow(color: Color.black.opacity(0.1), radius: 4, x: 0, y: 2)
    }
}

